---
Version: 0.0.1
Customers:
  - CP
  - CN
  - BNSF
  - UP
  - CSX
  - NS
Tags:
  CalgaryABCP: Calgary, AB
  GoldenBCCP: Golden, BC
  MooseJawSKCP: Moose Jaw, SK
  PocoBCCP: Port Coquitlam, BC
  StPaulMNCP: St Paul, MN
  TorontoONCP: Toronto, ON
Tables:
  ACD_Data:
    Registers:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
    ColumnNames:
      - ID
      - WheelSetID
      - ManualCutDataID
      - TimeACDCycleStarted
      - TimeClosed
      - ACDStartedFromChangeTarget
      - ACDStoppedByOperator
      - ACDStoppedByError
      - ACDFullyCompleted
      - ACDStoppedFromChangeTarget
      - FinishPassStarted
      - CutDiameterAtACDStart
      - SmallestCutDiameterWhenEntryClosed
      - ACDTargetDiameter
      - MaxRoughDOC
      - OptimumFinishDOC
      - MaximumFinishDOC
      - FinishPassRotations
      - InfeedUndershoot
      - CentersUpDistance
      - CuttersDownDistance
      - CalcRoughDOC
      - CalcRoughPasses
      - CalcFinishDOC
      - RoughPassesStarted
  Cycles:
    Registers:
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
    ColumnNames:
      - ID
      - TimeOfEntry
      - TimeLastOpened
      - TimeLastClosed
      - CycleType
      - VehicleID
      - Truck1ID
      - Truck2ID
      - WheelSet1ID
      - WheelSet2ID
      - WheelSet3ID
      - WheelSet4ID
      - WheelSet5ID
      - WheelSet6ID
      - VehicleType
      - VehicleNumber
      - Truck1SerialNumber
      - Truck2SerialNumber
      - Axle1SerialNumber
      - Axle2SerialNumber
      - Axle3SerialNumber
      - Axle4SerialNumber
      - Axle5SerialNumber
      - Axle6SerialNumber
      - LeftWhl1SerialNumber
      - LeftWhl2SerialNumber
      - LeftWhl3SerialNumber
      - LeftWhl4SerialNumber
      - LeftWhl5SerialNumber
      - LeftWhl6SerialNumber
      - RightWhl1SerialNumber
      - RightWhl2SerialNumber
      - RightWhl3SerialNumber
      - RightWhl4SerialNumber
      - RightWhl5SerialNumber
      - RightWhl6SerialNumber
  ManualCutData:
    Registers:
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
    ColumnNames:
      - ID
      - InfeedMonitoringDataLogged
      - WheelSetIDValid
      - WheelSetID
      - TimeSpindlesStarted
      - TimeSpindlesStopped
      - TimeOfFirstInfeedMonitoring
      - CutDiameterWhenSpindlesStarted
      - CutDiameterAtFirstInfeedMonitoring
      - SmallestCutDiameterWhenEntryClosed
  VehicleData:
    Registers:
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 134
      - 78
      - 79
      - 80
      - 81
      - 82
    ColumnNames:
      - ID
      - TimeOfEntry
      - TimeLastUpdated
      - VehicleType
      - VehicleNumber
      - Operator
      - UserIDNum
      - VehicleOdometer
      - OperatingHours
      - Truck1ID
      - Truck2ID
      - MaxDiamDiffInVehicle
  TruckData:
    Registers:
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 136
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
    ColumnNames:
      - ID
      - TimeOfEntry
      - TimeLastUpdated
      - VehicleType
      - TruckSerialNumber
      - Operator
      - UserIDNum
      - ThreeAxlesPerTruck
      - TruckNumberInVehicle
      - MaxDiamDiffInTruck
      - WheelSet1ID
      - WheelSet2ID
      - WheelSet3ID
  WheelSetData:
    Registers:
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 135
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      - 118
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      - 127
      - 128
      - 129
      - 130
      - 131
      - 132
      - 133
    ColumnNames:
      - ID
      - TimeOfEntry
      - TimeLastUpdated
      - VehicleType
      - AxleSerialNumber
      - LeftWhlSerialNumber
      - RightWhlSerialNumber
      - Operator
      - UserIDNum
      - WheelSetCut
      - ReferenceGrooveUsed
      - WheelSetNumberInVehicle
      - WheelReferenceDiameter
      - WheelMinimumRimThickness
      - WheelSetShim
      - WheelSetTargetDiameter
      - WheelSetTargetServiceMetalRemaining
      - WheelSetFinishedDiameter
      - WheelSetFinishedServiceMetalRemaining
      - LeftWhlWhyMadeCode
      - LeftWhlStartingServiceMetal
      - LeftWhlStartingRimThicknessWithRefGroove
      - LeftWhlStartingFlangeHeight
      - LeftWhlStartingFlangeThickness
      - LeftWhlStartingDiameter
      - LeftWhlStartingCutDepth
      - LeftWhlTargetDiameter
      - LeftWhlActualMaterialRemoved
      - RightWhlWhyMadeCode
      - RightWhlStartingServiceMetal
      - RightWhlStartingRimThicknessWithRefGroove
      - RightWhlStartingFlangeHeight
      - RightWhlStartingFlangeThickness
      - RightWhlStartingDiameter
      - RightWhlStartingCutDepth
      - RightWhlTargetDiameter
      - RightWhlActualMaterialRemoved
      - StartingDiameterLocked
      - CutDepthLocked
      - WheelSetTargetDiameterLocked
